version: '3'

services:
  ddshopdb:
    container_name: ddshopdb
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: dangerous
      MYSQL_DATABASE: ddshop # for database creation automatically

    # 端口映射
    ports:
      - 3306:3306
    # 数据挂载
    volumes:
      # - "./data:/var/lib/mysql"
      - "/tmp/mysql/data:/var/lib/mysql"

  cache:
    container_name: cache
    image: redis:latest
    ports: 
      - "6379:6379"
    volumes:
      - /tmp/redis/data:/data
    command: redis-server --appendonly yes 


  # consul:
  #   container_name: consul
  #   image: consul:latest
  #   ports:
  #     - 8500:8500  # web
  #   command: ["consul","agent","-server","-bootstrap","-data-dir","/consul","-ui","-bind","127.0.0.1","-client","0.0.0.0"]
